services:
  - type: web
    name: rolimons-social-scraper
    env: node
    buildCommand: docker build -t rolimons-scraper .
    startCommand: npm start
    envVars:
      - key: WEBHOOK_URL
        value: https://discord.com/api/webhooks/1404188843451744377/egOgRSomhoOCJvjL4ssBVHUnpCcvWYBZsBJ8pgEJNEsFScezJQy6w0NS3JYlSpSc9Yz3
      - key: MAX_VALUE
        value: 7000000
      - key: MAX_TRADE_ADS
        value: 1000
      - key: AUTH_TOKEN
        value: ""
      - key: NODE_ENV
        value: production 