services:
  - type: background
    name: rolimons-social-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: null
    envVars:
      - key: WEBHOOK_URL
        value: https://discord.com/api/webhooks/1404188843451744377/egOgRSomhoOCJvjL4ssBVHUnpCcvWYBZsBJ8pgEJNEsFScezJQy6w0NS3JYlSpSc9Yz3
      - key: MAX_VALUE
        value: 7000000
      - key: MAX_TRADE_ADS
        value: 1000
      - key: AUTH_TOKEN
        value: ""
      - key: ITEM_IDS
        value: "123456,789012"
      - key: NODE_ENV
        value: production 